### ISSUE TITLE
Missing licensing in PAM code.

### ISSUE THREAD

**Issue by parazyd** [dyne/sud#11]
You might want to give credit to Nathan ;)

https://github.com/Duncaen/OpenDoas/raw/master/pam.c

**Comment by jaromil** [comment]
sincerely, that's not where the PAM code comes from

**Comment by parazyd** [comment]
![17lwv6](https://user-images.githubusercontent.com/9220323/107038921-843cf780-67bd-11eb-83a6-12837924e2e0.jpg)


I noticed a striking familiarity when reviewing this code. Apologies.

**Comment by jaromil** [comment]
Nevertheless thanks for the pointer, PAM lacks a lot of documentation and the doas implementation has some additional knowledge on corner cases and may be a good future reference. I like to keep all sud as public domain, so I have written it pretty much all by myself looking at manpages and other public domain code. But I am already planning a BSD or GPL licensed  implementation with more features, however it will be requiring [pamela](/skarnet/pamela) for PAM.
